language: go
go:
  - release
  - tip
before_install:
  - gotools=golang.org/x/tools
  - if [ "$TRAVIS_GO_VERSION" = "release" ] || [ "$TRAVIS_GO_VERSION" = "go1.3.3" ]; then gotools=code.google.com/p/go.tools; fi
install:
  - go get -d -t -v ./...
  - go get -v $gotools/cmd/cover
  - go get -v $gotools/cmd/vet
  - go get -v github.com/bradfitz/goimports
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=xdr2/profile.cov -service=travis-ci
